version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: media-radar-frontend
    ports:
      - "3000:3000"
    environment:
      # Load environment variables from .env file
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://backend:5000}
      - REACT_APP_ENV=${REACT_APP_ENV:-production}
      - REACT_APP_NAME=${REACT_APP_NAME:-Media Radar}
      - REACT_APP_VERSION=${REACT_APP_VERSION:-1.0.0}
    env_file:
      - .env  # Load additional variables from .env file
    restart: unless-stopped
    networks:
      - media-radar-network
    depends_on:
      - backend
    labels:
      - "com.docker.compose.service=frontend"
      - "com.application=media-radar"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend service reference (assuming it exists)
  backend:
    image: media-radar-backend:latest  # Replace with actual backend image
    container_name: media-radar-backend
    ports:
      - "5000:5000"
    networks:
      - media-radar-network
    # Backend configuration would be defined in backend's docker-compose.yml

networks:
  media-radar-network:
    driver: bridge 